version: '2'

services:
    delugevpn:
        image: binhex/arch-delugevpn
        container_name: delugevpn
            - NET_ADMIN
        ports:
            - 8112:8112
            - 8118:8118
            - 58846:58846
            - 58946:58946
        volumes:
            - /srv/appdata/delugevpn:/config
            - /srv/downloads:/data
            - /etc/localtime:/etc/localtime:ro
        env_file: envfiles/delugevpn.env
        environment:
            PUID: ${userid}
            PGID: ${groupid}
            TZ: ${time}
            UMASK: '000'
            VPN_ENABLED: 'yes'
            VPN_PROV: 'pia'
            ENABLE_PRIVOXY: 'yes'
            STRICT_PORT_FORWARDING: 'yes'            
            NAME_SERVERS: '8.8.8.8,8.8.4.4,209.222.18.222'