version: '2'

services:
    resiliosync:
        image: linuxserver/resilio-sync
        container_name: resiliosync
        restart: always
        networks:
            - media
        ports:
            - 7777:8888
            - 55555:55555
        volumes:
            - /srv/appdata/resiliosync:/config
            - /srv/syncfolder:/sync
        environment:
            PUID: ${userid}
            PGID: ${groupid}
            UMASK_SET: 022

networks:
    media:
        external: true            
                